### ISSUE TITLE
does extends work?

### ISSUE THREAD

**Issue by nmccready** [bline/jade-html-loader#8]
Since trying to use extends I am receiving.

```
Module build failed: TypeError: Cannot read property 'call' of undefined
  at eval (<anonymous>:8:23)
  at res (/Users/nem/code/github/rmaps/map/node_modules/jade/lib/index.js:219:38)
  at Object.module.exports (/Users/nem/code/github/rmaps/map/node_modules/jade-html-loader/index.js:19:9)
 @ multi main
```

**Comment by nmccready** [comment]
NVM dumb error. Turning on compileDebug made it obvious. I had to turn it on through index.js in node_moduels. How would I do this from the webpack conf?

`{ test: /\.jade$/, loader: "html?attrs=img:src!jade-html" }` ?
